"""empty message

Revision ID: a89f9ece2104
Revises: 57f6f192ca1e
Create Date: 2026-01-22 13:56:30.235398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89f9ece2104'
down_revision = '57f6f192ca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('caminho', sa.String(length=255), nullable=True),
    sa.Column('extensao', sa.String(length=8), nullable=True),
    sa.Column('tamanho', sa.Float(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_arquivo')
    # ### end Alembic commands ###
