"""empty message

Revision ID: d1e9aa94ac19
Revises: a89f9ece2104
Create Date: 2026-01-22 14:11:22.140375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e9aa94ac19'
down_revision = 'a89f9ece2104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'upload_arquivo', ['foto_perfil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('foto_perfil_id')

    # ### end Alembic commands ###
